[package]
name = "balas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
argh = "0.1.12"
bit-vec = "0.6.3"
lp_parser_rs = "0.1.3"
num = "0.4.1"
thiserror = "1.0.52"
